<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>95f0f60d-e315-4f44-959d-a559e6d122ec</elementGuidId>
    <imagePath></imagePath>
    <name>input_SearchDocs</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[3]/div[1]/header[1]/form[1]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#docsearch-input</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'docsearch-input') and equals(@type,'search')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:attr=[placeholder="Search docs"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>docsearch-input</value>
        <webElementGuid>d487bee6-c4a0-428d-a009-9e4283a03239</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>search</value>
        <webElementGuid>d487bee6-c4a0-428d-a009-9e4283a03239</webElementGuid>
    </webElementProperties>
</WebElementEntity>