<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>d06cdfc3-1ce6-4be7-842c-8249b3718581</elementGuidId>
    <imagePath></imagePath>
    <name>link_Slide</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[15]/div[1]/div[3]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="css-1dbjc4n\ r-182zmgx\ r-1loqt21\ r-1otgn73"] &gt; [class="css-4rbku5\ css-1dbjc4n\ r-o7k8zt\ r-owlft4\ r-1xq2hnv\ r-hg93c8"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/slide') and equals(@text,'Slide')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="Slide"s]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/slide</value>
        <webElementGuid>d487bee6-c4a0-428d-a009-9e4283a03239</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Slide</value>
        <webElementGuid>d487bee6-c4a0-428d-a009-9e4283a03239</webElementGuid>
    </webElementProperties>
</WebElementEntity>