<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>95c17b07-193f-4dfb-8579-01953ec1ef48</elementGuidId>
    <imagePath></imagePath>
    <name>link_Slider</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[8]/div[1]/div[11]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="css-1dbjc4n\ r-182zmgx\ r-1loqt21\ r-1otgn73"] &gt; [class="css-4rbku5\ css-1dbjc4n\ r-o7k8zt\ r-owlft4\ r-1xq2hnv\ r-hg93c8"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/slider') and equals(@text,'Slider')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="Slider"s]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/slider</value>
        <webElementGuid>344c672c-1d7c-471f-a718-ac54a329f805</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Slider</value>
        <webElementGuid>344c672c-1d7c-471f-a718-ac54a329f805</webElementGuid>
    </webElementProperties>
</WebElementEntity>