<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>2a8afdac-5a9c-48a7-ab3d-dac4f59f65a1</elementGuidId>
    <imagePath></imagePath>
    <name>select_serviceOptions</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[3]/div[2]/div[2]/div[1]/div[1]/div[1]/pre[1]/div[1]/div[1]/div[1]/div[1]/div[1]/select[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="css-1dbjc4n\ r-14nekm4\ r-1544tr9"] &gt; select</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>pre &gt;&gt; internal:has-text="${select_serviceOptions_internalHasText}"i &gt;&gt; internal:label="Choose Service"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>