<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>2296773f-3a03-43cd-8a2a-fa02ea700df5</elementGuidId>
    <imagePath></imagePath>
    <name>div_ContentBlock1</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[3]/div[2]/div[2]/div[1]/div[1]/div[1]/pre[3]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="css-1dbjc4n\ r-1awozwy\ r-9lim0t\ r-sdzlij\ r-1loqt21\ r-19uokag\ r-1777fci\ r-1me8fb3\ r-1tihekz\ r-il82ww\ r-u8s1d\ r-104ivgm\ r-c97pre"] [class="css-1dbjc4n\ r-sdzlij\ r-o7k8zt\ r-1pzp21b\ r-1wkhzzn\ r-hg93c8\ r-u8s1d\ r-1wyyakw"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>pre:nth-child(9) &gt; div &gt; div:nth-child(2) &gt; div &gt; div &gt; div:nth-child(2) &gt; div &gt; div &gt;&gt; nth=0</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>