<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>c22fb0c0-2973-4b3d-940b-652e133685a5</elementGuidId>
    <imagePath></imagePath>
    <name>link_Select</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[8]/div[1]/div[10]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="css-1dbjc4n\ r-182zmgx\ r-1loqt21\ r-1otgn73"] &gt; [class="css-4rbku5\ css-1dbjc4n\ r-o7k8zt\ r-owlft4\ r-1xq2hnv\ r-hg93c8"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/select') and equals(@text,'Select')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="Select"s]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/select</value>
        <webElementGuid>b5c3f73e-038c-4c7e-8953-37a1d25a40da</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Select</value>
        <webElementGuid>b5c3f73e-038c-4c7e-8953-37a1d25a40da</webElementGuid>
    </webElementProperties>
</WebElementEntity>